# Generated by Django 4.2.3 on 2023-07-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profiles/avatar.png', upload_to='profiles')),
                ('position', models.CharField(choices=[('Staff', 'staff'), ('Manager', 'manager'), ('Administrator', 'administrator')], default=1, max_length=20)),
            ],
        ),
    ]
