# Generated by Django 4.2.3 on 2023-07-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('Staff', 'staff'), ('Manager', 'manager'), ('Administrator', 'administrator')], default='staff', max_length=20),
        ),
    ]
