# Generated by Django 4.2.19 on 2025-02-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0014_alter_vouchercategory_options_and_more"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="voucher",
        ),
        migrations.AddField(
            model_name="sale",
            name="voucher",
            field=models.ManyToManyField(to="vouchers.vouchers"),
        ),
    ]
