# Generated by Django 4.2.19 on 2025-02-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_remove_sale_voucher_sale_voucher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="type",
            field=models.CharField(
                choices=[
                    ("hourly", "hourly"),
                    ("day desk", "day desk"),
                    ("meeting room", "meeting room"),
                    ("monthly", "monthly"),
                ],
                max_length=50,
            ),
        ),
    ]
