# Generated by Django 4.2.3 on 2023-07-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchers',
            name='user',
        ),
    ]
