# Generated by Django 4.2.3 on 2023-07-30 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_remove_vouchers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.voucherfile'),
        ),
    ]
