# Generated by Django 4.2 on 2023-08-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0006_voucherlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherlogs',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
