# Generated by Django 4.2 on 2023-08-06 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0008_voucheruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucheruser',
            old_name='voucher',
            new_name='voucher_no',
        ),
    ]
