# Generated by Django 4.2 on 2023-08-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0009_rename_voucher_voucheruser_voucher_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucheruser',
            name='voucher_no',
            field=models.CharField(max_length=50),
        ),
    ]
