# Generated by Django 4.2.2 on 2023-08-07 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0010_alter_voucheruser_voucher_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucherfile',
            options={'ordering': ['-date_created'], 'verbose_name': 'voucherFile', 'verbose_name_plural': 'voucherFiles'},
        ),
        migrations.AlterModelOptions(
            name='voucherlogs',
            options={'ordering': ['-date_created'], 'verbose_name': 'voucherLogs', 'verbose_name_plural': 'voucherLogss'},
        ),
        migrations.AlterModelOptions(
            name='vouchers',
            options={'ordering': ['-date_created'], 'verbose_name': 'vouchers', 'verbose_name_plural': 'vouchers'},
        ),
        migrations.AddField(
            model_name='voucheruser',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
