# Generated by Django 4.2.2 on 2025-10-21 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PfSenseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default pfSense', max_length=100)),
                ('host', models.CharField(help_text='pfSense host/IP', max_length=255)),
                ('port', models.IntegerField(default=443)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('use_ssl', models.BooleanField(default=True)),
                ('verify_ssl', models.BooleanField(default=False)),
                ('captive_portal_zone', models.CharField(default='zone1', help_text='Captive portal zone name', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'PfSense Configuration',
                'verbose_name_plural': 'PfSense Configurations',
            },
        ),
        migrations.CreateModel(
            name='VoucherCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'VoucherCategory',
                'verbose_name_plural': 'VoucherCategories',
            },
        ),
        migrations.CreateModel(
            name='VoucherFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='vouchers')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='not populated', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.vouchercategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VoucherFile',
                'verbose_name_plural': 'VoucherFiles',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Vouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=100, unique=True)),
                ('voucher_password', models.CharField(blank=True, max_length=50, null=True)),
                ('voucher_username', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_used', models.DateTimeField(blank=True, null=True)),
                ('date_printed', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unused', 'Unused'), ('used', 'Used'), ('expired', 'Expired'), ('printed', 'Printed')], default='unused', max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('validity_duration', models.IntegerField(default=24, help_text='Validity in hours')),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('bandwidth_up', models.IntegerField(blank=True, help_text='Upload bandwidth in Kbps', null=True)),
                ('bandwidth_down', models.IntegerField(blank=True, help_text='Download bandwidth in Kbps', null=True)),
                ('pfsense_roll_id', models.IntegerField(blank=True, null=True)),
                ('synced_to_pfsense', models.BooleanField(default=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.voucherfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='VoucherUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('device_mac', models.CharField(blank=True, max_length=17, null=True)),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('voucher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_user', to='vouchers.vouchers')),
            ],
            options={
                'verbose_name': 'VoucherUser',
                'verbose_name_plural': 'VoucherUsers',
            },
        ),
        migrations.CreateModel(
            name='VoucherLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('action_type', models.CharField(choices=[('create', 'Created'), ('populate', 'Populated'), ('print', 'Printed'), ('use', 'Used'), ('sync', 'Synced to pfSense'), ('expire', 'Expired')], default='create', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vouchers.vouchers')),
            ],
            options={
                'verbose_name': 'VoucherLog',
                'verbose_name_plural': 'VoucherLogs',
                'ordering': ['-date_created'],
            },
        ),
    ]
