# Generated by Django 4.2 on 2023-08-06 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0007_alter_voucherlogs_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='voucherUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.vouchers')),
            ],
            options={
                'verbose_name': 'voucherUser',
                'verbose_name_plural': 'voucherUsers',
            },
        ),
    ]
