# Generated by Django 4.2.2 on 2023-08-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0011_alter_voucherfile_options_alter_voucherlogs_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucheruser',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
